### ISSUE TITLE
Better key for list rendering

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#10]
Images have their own IDs. Use them wisely.
Avoid using indexes when unique IDs are available.
https://github.com/dacsang97/unsplash-gallery/blob/523e3b586cea6df5102c4ef5ceaa8abf225e722c/src/components/UIComponents/CardList.vue#L3
Read more: https://vuejs.org/v2/guide/list.html#key

**Comment by dacsang97** [comment]
I updated and used image id instead of element's index aec2921f566a82f2940c3261e780d062a3a4205b
