### ISSUE TITLE
Better API injection

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#12]
The current approach of API injection limits the extension of the application since the API plugin modifies the global variable `Vue.http.headers.common`. What if there are multiple APIs instead of one? Consider refactoring this.

**Comment by dacsang97** [comment]
I replaced vue-resource with axios 65e4b89a7aa07f90299bf3d3704e8a0ee5064d65

**Comment by hiendv** [comment]
It seems good but there is another way. Further discussion next time.
