### ISSUE TITLE
Proper error handler

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#4]
Error messages are well documented here: https://unsplash.com/documentation#error-messages
These redundant lines could be improved.
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Author.vue#L5
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Author.vue#L58-L60
The error code should also be more precise.

**Comment by dacsang97** [comment]
I had handled error messages to show them in this commit 7d38e719694fd656c30a29ecc808e33a9ce6e539

**Comment by hiendv** [comment]
Read my comments in https://github.com/dacsang97/unsplash-gallery/commit/7d38e719694fd656c30a29ecc808e33a9ce6e539

**Comment by dacsang97** [comment]
This issue should address by my commit https://github.com/dacsang97/unsplash-gallery/commit/f169333227c66b8aa42ca20f98a55feeb0cc0e3a https://github.com/dacsang97/unsplash-gallery/commit/dddfa444d7da90e561585a2cce406f757d1d3378

**Comment by hiendv** [comment]
The discussion continues in the commit.

**Comment by hiendv** [comment]
The [mixin](https://github.com/dacsang97/unsplash-gallery/blob/55ac28b8a8f8ad02800d2980974aff78a703ecce/src/mixin/viewMixin.js) is DRY but it would be better if view conditions are computed. My suggestion: 
```js
computed: {
    hasErrors () {
        return this.errors && this.errors.status && this.errors.status !== 200
    }
}
```
What's your opinion on this?

**Comment by dacsang97** [comment]
Thanks for your feedback, I updated it in 57a3f7910a960dd419441b91332dc9963f4c3094
