### ISSUE TITLE
Development code bloat

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#5]
Avoid these comments
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Author.vue#L50-L53

**Comment by hiendv** [comment]
Also thanks for your extra 1.27KB
https://github.com/dacsang97/unsplash-gallery/blob/72e090274745c61e002aca6ae119c956a7f4ba4b/src/components/Hello.vue

**Comment by hiendv** [comment]
Again: https://github.com/dacsang97/unsplash-gallery/blob/a743940b552c89002cfdf7b823f0e3c7bec5559d/src/components/Layouts/AppLayout.vue

**Comment by dacsang97** [comment]
7bc4bdc2c3a04f77771619a02732131cd61cd14d

**Comment by hiendv** [comment]
Again, you are mixing everything up. Changes in [src/router/index.js](https://github.com/dacsang97/unsplash-gallery/commit/7bc4bdc2c3a04f77771619a02732131cd61cd14d#diff-36727cbb21483337586ca81cb95f29b4) do not belong here
