### ISSUE TITLE
Current page remembering when using infinite loading

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#6]
When using infinite loading, it will be impossible for users to navigate to a specific pagination. We can ease the pain with a better routing which contains `page`.
Some places could be improved:
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Home.vue#L30
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Author.vue#L49
There may be more.

**Comment by hiendv** [comment]
To be precise, I will give an example. Let's say, user A came to the website and browse photos from the homepage. He saw some great photos after scrolling for a while. He wanted to share with user B by copying the address.
What was it? `https://unsplash-gallery.firebaseapp.com/`
User B entered the site and only saw photos from the first page. No clue what user A talked about. That's the problem. It may be known as [mental location](https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1#d12e) (you can read more about related problems in this article).

Anyway, pagination using `page` indicator is not actually good. I would recommend using cursor but the API does not provide this mechanism so using `page` is okay.

**Comment by dacsang97** [comment]
Current page remembered in new commit f89f819a1e5d857e8b614a6f7bc16afd64280330

**Comment by hiendv** [comment]
It seems like Unsplash changed their API so I could not check the result.

**Comment by hiendv** [comment]
@dacsang97 I think we should update the API Authorization then :smile:

**Comment by hiendv** [comment]
My bad. It's not because of authorization.
