### ISSUE TITLE
Fail fast / Return early

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#7]
Using **else**s and **nested-if**s is a crime.
Some places could be improved:
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Home.vue#L39-L49
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/Views/Author.vue#L43-L56
There may be more.

**Comment by dacsang97** [comment]
This issue should address in 93b63eea8e05a79b7b512eef98a70db241638cc7

**Comment by hiendv** [comment]
Nope. It still looks bad. There is another way. **Return early!**

**Comment by dacsang97** [comment]
Is it correct 183a8edf8b2628a09d04d9f5cf297a8d85c61ec9?

**Comment by hiendv** [comment]
Defensive check on result needed: https://github.com/dacsang97/unsplash-gallery/blob/183a8edf8b2628a09d04d9f5cf297a8d85c61ec9/src/components/Views/Author.vue#L49

**Comment by dacsang97** [comment]
Update in f86ea39582af65acead53fc155d318d36093d175

**Comment by hiendv** [comment]
The discussion continues with comments in https://github.com/dacsang97/unsplash-gallery/commit/f86ea39582af65acead53fc155d318d36093d175.

**Comment by dacsang97** [comment]
I fixed it
https://github.com/dacsang97/unsplash-gallery/blob/c3715bcb456978436c7d71806f88a64774c0a76a/src/components/Views/Author.vue#L51-L53
https://github.com/dacsang97/unsplash-gallery/blob/c3715bcb456978436c7d71806f88a64774c0a76a/src/components/Views/Home.vue#L43-L45
