### ISSUE TITLE
Defensive programming

### ISSUE THREAD

**Issue by hiendv** [dacsang97/unsplash-gallery#8]
Avoid chaining calls like this.
```js
foo.bar.qux
```
What if `foo.bar` is undefined?
Some places could be improve:
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/UIComponents/CardImage/CardHeader.vue#L3-L4
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/UIComponents/CardImage/index.vue#L4
https://github.com/dacsang97/unsplash-gallery/blob/6701a845d76a908ffb3220569ee7c9668f728bbf/src/components/UIComponents/UserInfo.vue#L4
There may be more.

**Comment by hiendv** [comment]
Using **computed properties** when possible.

**Comment by dacsang97** [comment]
I had undefined object in edc11967d2f4700cd2a952103673f7323523c1d9

**Comment by dacsang97** [comment]
I use lodash.get for getting Object props.
In this line 
https://github.com/dacsang97/unsplash-gallery/blob/c3715bcb456978436c7d71806f88a64774c0a76a/src/components/Views/Author.vue#L57
If **user** is null, CardInfo will not render.

**Comment by hiendv** [comment]
`lodash.get` is not actually useful here. We just need simple checks, IMO. See my comment: https://github.com/dacsang97/unsplash-gallery/commit/c3715bcb456978436c7d71806f88a64774c0a76a#commitcomment-24210635

**Comment by hiendv** [comment]
Nevermind. lodash.get does check for input object. But that would be better if you see it this way
```js
this.user = this.getProp(result, '[0].user')
```

**Comment by hiendv** [comment]
Nevertheless, `lodash.get` performance is quite poor: https://jsperf.com/lodash-get-vs-native-or/3
